import uuid
from datetime import UTC, date, datetime
from decimal import Decimal

from sqlalchemy import (
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Numeric,
    String,
    Text,
    Uuid,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base

MONEY_PRECISION = Numeric(19, 4)


def utc_now() -> datetime:
    return datetime.now(UTC)


class LoanPayment(Base):
    """Money received from a customer (DATABASE.md §28).

    Status values follow PAYMENT_RULES.md §7 (business authority):
    POSTED / REVERSED. DATABASE.md §28 sketches ACTIVE/REVERSED; the
    business-rules naming wins and the difference is documented here.

    Payments are never physically deleted; corrections happen through
    explicit reversals (PAYMENT_RULES.md §41–45).
    """

    __tablename__ = "loan_payments"
    __table_args__ = (
        CheckConstraint("amount > 0", name="ck_payments_amount_positive"),
        CheckConstraint("payment_method IN ('CASH', 'BANK_TRANSFER', 'CARD', 'OTHER')", name="ck_payments_method"),
        CheckConstraint("status IN ('POSTED', 'REVERSED')", name="ck_payments_status"),
        # Idempotency (DATABASE.md §49): retries never duplicate payments.
        Index("uq_payments_user_idempotency", "user_id", "idempotency_key", unique=True),
        Index("ix_loan_payments_loan_date", "loan_id", "payment_date"),
    )

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
    )
    loan_id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        ForeignKey("loans.id", ondelete="RESTRICT"),
        nullable=False,
    )
    client_id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        ForeignKey("clients.id", ondelete="RESTRICT"),
        nullable=False,
    )
    amount: Mapped[Decimal] = mapped_column(MONEY_PRECISION, nullable=False)
    payment_date: Mapped[date] = mapped_column(Date, nullable=False)
    payment_method: Mapped[str] = mapped_column(String(16), nullable=False)
    reference: Mapped[str | None] = mapped_column(String(255), nullable=True)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="POSTED")
    # Credit generated by an overpayment (PAYMENT_RULES.md §27–29).
    credit_amount: Mapped[Decimal] = mapped_column(MONEY_PRECISION, nullable=False, default=0)
    idempotency_key: Mapped[str | None] = mapped_column(String(255), nullable=True)
    reversed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    reversal_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now, onupdate=utc_now
    )


class PaymentAllocation(Base):
    """How much of a payment went to each obligation component
    (DATABASE.md §30–32). Historical evidence: never rewritten."""

    __tablename__ = "payment_allocations"
    __table_args__ = (
        CheckConstraint("principal_amount >= 0", name="ck_allocations_principal"),
        CheckConstraint("interest_amount >= 0", name="ck_allocations_interest"),
        CheckConstraint("late_fee_amount >= 0", name="ck_allocations_late_fee"),
        Index("ix_allocations_payment", "payment_id"),
        Index("ix_allocations_installment", "installment_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    payment_id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        ForeignKey("loan_payments.id", ondelete="RESTRICT"),
        nullable=False,
    )
    installment_id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        ForeignKey("loan_installments.id", ondelete="RESTRICT"),
        nullable=False,
    )
    principal_amount: Mapped[Decimal] = mapped_column(MONEY_PRECISION, nullable=False, default=0)
    interest_amount: Mapped[Decimal] = mapped_column(MONEY_PRECISION, nullable=False, default=0)
    late_fee_amount: Mapped[Decimal] = mapped_column(MONEY_PRECISION, nullable=False, default=0)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now, onupdate=utc_now
    )


__all__ = ["LoanPayment", "PaymentAllocation"]
