"""loan payments allocations and transaction sources

Revision ID: 4f06e9975002
Revises: da8f401836e6
Create Date: 2026-08-23 20:37:35.213831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f06e9975002'
down_revision: Union[str, Sequence[str], None] = 'da8f401836e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('loan_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=16), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("payment_method IN ('CASH', 'BANK_TRANSFER', 'CARD', 'OTHER')", name='ck_payments_method'),
    sa.CheckConstraint("status IN ('POSTED', 'REVERSED')", name='ck_payments_status'),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_loan_payments_loan_date', 'loan_payments', ['loan_id', 'payment_date'], unique=False)
    op.create_index('uq_payments_user_idempotency', 'loan_payments', ['user_id', 'idempotency_key'], unique=True)
    op.create_table('payment_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('installment_id', sa.Uuid(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('interest_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('late_fee_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('interest_amount >= 0', name='ck_allocations_interest'),
    sa.CheckConstraint('late_fee_amount >= 0', name='ck_allocations_late_fee'),
    sa.CheckConstraint('principal_amount >= 0', name='ck_allocations_principal'),
    sa.ForeignKeyConstraint(['installment_id'], ['loan_installments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['loan_payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_allocations_installment', 'payment_allocations', ['installment_id'], unique=False)
    op.create_index('ix_allocations_payment', 'payment_allocations', ['payment_id'], unique=False)
    op.add_column('transactions', sa.Column('source_type', sa.String(length=32), nullable=True))
    op.add_column('transactions', sa.Column('source_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'source_id')
    op.drop_column('transactions', 'source_type')
    op.drop_index('ix_allocations_payment', table_name='payment_allocations')
    op.drop_index('ix_allocations_installment', table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index('uq_payments_user_idempotency', table_name='loan_payments')
    op.drop_index('ix_loan_payments_loan_date', table_name='loan_payments')
    op.drop_table('loan_payments')
    # ### end Alembic commands ###
