"""categories transactions goals contributions

Revision ID: 4fbe8275a09f
Revises: 15b9c74d11e2
Create Date: 2026-08-22 16:41:04.795817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fbe8275a09f'
down_revision: Union[str, Sequence[str], None] = '15b9c74d11e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    # Case-insensitive uniqueness of ACTIVE categories per user+type
    # (DATABASE.md §11). Partial index: deactivated categories keep their
    # historical names without blocking new ones.
    op.create_index(
        'uq_categories_user_type_lower_name',
        'categories',
        ['user_id', 'type', sa.text('LOWER(name)')],
        unique=True,
        postgresql_where=sa.text('is_active'),
    )
    op.create_table('financial_goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'COMPLETED', 'CANCELLED')", name='ck_goals_status'),
    sa.CheckConstraint('target_amount > 0', name='ck_goals_target_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_financial_goals_user_status', 'financial_goals', ['user_id', 'status'], unique=False)
    op.create_table('goal_contributions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('contribution_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'CANCELLED')", name='ck_contributions_status'),
    sa.CheckConstraint('amount > 0', name='ck_contributions_amount_positive'),
    sa.ForeignKeyConstraint(['goal_id'], ['financial_goals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_goal_contributions_goal_date', 'goal_contributions', ['goal_id', 'contribution_date'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("payment_method IS NULL OR payment_method IN ('CASH', 'BANK_TRANSFER', 'CARD', 'OTHER')", name='ck_transactions_payment_method'),
    sa.CheckConstraint("status IN ('ACTIVE', 'CANCELLED')", name='ck_transactions_status'),
    sa.CheckConstraint("type IN ('INCOME', 'EXPENSE')", name='ck_transactions_type'),
    sa.CheckConstraint('amount > 0', name='ck_transactions_amount_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_user_date', 'transactions', ['user_id', 'transaction_date'], unique=False)
    op.create_index('ix_transactions_user_type_date', 'transactions', ['user_id', 'type', 'transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_user_type_date', table_name='transactions')
    op.drop_index('ix_transactions_user_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_goal_contributions_goal_date', table_name='goal_contributions')
    op.drop_table('goal_contributions')
    op.drop_index('ix_financial_goals_user_status', table_name='financial_goals')
    op.drop_table('financial_goals')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_index('uq_categories_user_type_lower_name', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
