"""loans installments late fee configs audit logs

Revision ID: da8f401836e6
Revises: 3a7c1f9d4b21
Create Date: 2026-08-23 19:58:48.616547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da8f401836e6'
down_revision: Union[str, Sequence[str], None] = '3a7c1f9d4b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('principal', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('interest_period', sa.String(length=16), nullable=False),
    sa.Column('amortization_type', sa.String(length=32), nullable=False),
    sa.Column('payment_frequency', sa.String(length=16), nullable=False),
    sa.Column('number_of_installments', sa.Integer(), nullable=False),
    sa.Column('first_due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('guarantee', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('number_of_installments > 0', name='ck_loans_installments_positive'),
    sa.CheckConstraint('principal > 0', name='ck_loans_principal_positive'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_loans_client_status', 'loans', ['client_id', 'status'], unique=False)
    op.create_index('ix_loans_user_status', 'loans', ['user_id', 'status'], unique=False)
    op.create_table('late_fee_configurations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('loan_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('grace_period_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id')
    )
    op.create_table('loan_installments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('loan_id', sa.Uuid(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal_due', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('interest_due', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('late_fee_due', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total_due', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('principal_paid', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('interest_paid', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('late_fee_paid', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('remaining_balance', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'PARTIAL', 'PAID', 'OVERDUE', 'CANCELLED')", name='ck_installments_status'),
    sa.CheckConstraint('installment_number > 0', name='ck_installments_number_positive'),
    sa.CheckConstraint('interest_due >= 0', name='ck_installments_interest_due'),
    sa.CheckConstraint('interest_paid >= 0', name='ck_installments_interest_paid'),
    sa.CheckConstraint('late_fee_due >= 0', name='ck_installments_late_fee_due'),
    sa.CheckConstraint('late_fee_paid >= 0', name='ck_installments_late_fee_paid'),
    sa.CheckConstraint('principal_due >= 0', name='ck_installments_principal_due'),
    sa.CheckConstraint('principal_paid >= 0', name='ck_installments_principal_paid'),
    sa.CheckConstraint('remaining_balance >= 0', name='ck_installments_remaining'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_loan_installments_loan_due', 'loan_installments', ['loan_id', 'due_date'], unique=False)
    op.create_index('ix_loan_installments_status_due', 'loan_installments', ['status', 'due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_loan_installments_status_due', table_name='loan_installments')
    op.drop_index('ix_loan_installments_loan_due', table_name='loan_installments')
    op.drop_table('loan_installments')
    op.drop_table('late_fee_configurations')
    op.drop_index('ix_loans_user_status', table_name='loans')
    op.drop_index('ix_loans_client_status', table_name='loans')
    op.drop_table('loans')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
